### ISSUE TITLE
Crashes on pasting links

### ISSUE THREAD

**Issue by mahoromax** [zolrath/obsidian-auto-link-title#49]
I've had Obsidian crash a few times just after pasting a hyperlink.
I also can't narrow it down to specific sites,  ( I recall a link to Zenodo.com, or a shortcode url for example)

I can only imagine that problems  were created by an obsidian update - since this plugin did not update recently.

Maybe others had a similar experience?

edit:
Crashed after pasting this URL: https://www.integromat.com/en
Opened Obsidian again, (the link text was stuck on "fetching title"), pasted again - crashed again.

**Comment by lkhrs** [comment]
What version of Obsidian are you on and which OS? I just pasted that URL and the title was resolved without issue.

I'm using Obsidian 0.14.6 and macOS 12.3.1.

**Comment by mahoromax** [comment]
Windows 10 and the up2date version of Obsidian at the time of posting (I did update Obsidian and all plugins in search of an easy fix).
Right now I'm on 0.14.6, v1.2.5 of the plugin

But I can still reproduce the crash.  
I'm now in my home network but I first reported this from office network, so I can kind of exclude external factors (I think ?)

**Comment by wenjoy** [comment]
Encounter the same problem. Windows 10 at version 0.15.9

**Comment by usernotnull** [comment]
+1, windows 11, plugin version 1.2.5 with obsidian v1.0.3

**Comment by lifo888** [comment]
Same happens on Mac.  It's happening consistently, everytime when i copy and paste a line with url and checkbox.  

About Obsidian
Version 1.1.8 (Installer 1.0.3)

**Comment by aizeklive** [comment]
Happens all the time on Windows

**Comment by zolrath** [comment]
Interesting, I use this on both Windows and macOS but haven't had it cause a crash.
Can you give me a way to reproduce it? Is it every link you post or is it in specific circumstances?

If you have a specific line that you're pasting a specific link into that causes a crash, if you are able to post it here so I can recreate that would be great!

Thanks!

**Comment by aizeklive** [comment]
> Interesting, I use this on both Windows and macOS but haven't had it cause a crash. Can you give me a way to reproduce it? Is it every link you post or is it in specific circumstances?
> 
> If you have a specific line that you're pasting a specific link into that causes a crash, if you are able to post it here so I can recreate that would be great!
> 
> Thanks!

It's strange but for some reason, plugin stopped crashing Obsidian and started to show "Site unreachable". Work on every link

**Comment by mahoromax** [comment]
The crashes stopped for me, eventually - I cannot say what caused the change though.

**Comment by zolrath** [comment]
Okay, hm, I'm going to close this for now but if it starts crashing again please let me know!

**Comment by wenjoy** [comment]
Observered crash on this link https://zhuanlan.zhihu.com/p/30135457
